name: Metropoly
version: '1.0'
main: pkg.metropoly.Metropoly
api-version: '1.21'
authors: [ Nadoo ]
description: Towny ma fatto meglio lol
commands:
  town:
    aliases: [t]
  wallet:
  materiali:
  mappa:
  hub:
  spawn:
  tutorial:
  metropoly:

softdepend: [PlaceholderAPI]
